server:
  port: 8107

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

spring:
  application:
    name: seasons-work
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seasons?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: zhangfu
    password: 1109039190

mybatis:
  type-aliases-package: com.zhang.seasonswork.model
  mapper-locations:
    - classpath:mybatis/*.xml

work:
  origin-stored: static/pay/
  free-stored: static/free/
  default-amount: 20
  prefix: http://192.168.0.102:8080/free/
