server:
  port: 8100
spring:
  application:
    name: seasons-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8100/eureka/